title: VKQuickLook
description: Native macOS Finder thumbnails and Quick Look previews for Keyence VK4 and VK6 measurement files.
url: https://vsoptomech.github.io
baseurl: /VKQuickLook

defaults:
  - scope:
      path: ""
    values:
      layout: default
